# Generated by Django 5.2.6 on 2025-10-29 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='restaurant_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
