# Generated by Django 5.1.1 on 2025-11-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ownerprofile_contact_number_and_more'),
        ('employees', '0009_remove_employee_date_started_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='employee',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='accounts.ownerprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(default='unknown@example.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(default='not available', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
    ]
