# Generated by Django 5.2.6 on 2025-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trash_pickups', '0002_voucher_trashpickup_pickup_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='RewardRedemption',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
