# Generated by Django 5.1.1 on 2025-10-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('trash_pickups', '0004_voucher_rewardredemption'),
    ]

    operations = [
        migrations.AddField(
            model_name='trashpickup',
            name='donation_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups', to='donations.donationdrive'),
        ),
    ]
