# Generated by Django 5.1.1 on 2025-10-30 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
        ('trash_pickups', '0005_trashpickup_donation_drive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trashpickup',
            name='donation_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_pickups', to='donations.donationdrive'),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='waste_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
