# Generated by Django 5.1.1 on 2025-11-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donationdrive_end_date_and_more'),
        ('trash_pickups', '0008_alter_trashpickup_scheduled_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashpickup',
            options={'ordering': ['-created_at'], 'verbose_name': 'Trash Pickup', 'verbose_name_plural': 'Trash Pickups'},
        ),
        migrations.AddField(
            model_name='trashpickup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude of the pickup location', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='trashpickup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude of the pickup location', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='donation_drive',
            field=models.ForeignKey(blank=True, help_text='If the pickup contributes to a donation drive', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_pickups', to='donations.donationdrive'),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='pickup_address',
            field=models.CharField(help_text='Address where the driver should pick up the waste', max_length=255),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='restaurant_name',
            field=models.CharField(help_text='Name of the restaurant that requested the pickup', max_length=255),
        ),
    ]
