# Generated by Django 5.1.1 on 2025-11-05 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donationdrive_end_date_and_more'),
        ('trash_pickups', '0009_alter_trashpickup_options_trashpickup_latitude_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trashpickup',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='donation_drive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trash_pickups', to='donations.donationdrive'),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='pickup_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trashpickup',
            name='restaurant_name',
            field=models.CharField(max_length=255),
        ),
    ]
