# Generated by Django 5.1.1 on 2025-11-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='ownerprofile',
            name='created_at',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='restaurant_name',
            field=models.CharField(max_length=255),
        ),
    ]
