# Generated by Django 5.1.1 on 2025-11-05 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_ownerprofile_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
