# Generated by Django 5.1.1 on 2025-11-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ownerprofile_latitude_ownerprofile_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
