# Generated by Django 5.2.6 on 2025-11-06 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_ownerprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerprofile',
            name='status',
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='address',
            field=models.CharField(default='Unknown Address', max_length=255),
            preserve_default=False,
        ),
    ]
