# Generated by Django 5.1.1 on 2025-11-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationdrive',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='donationdrive',
            name='start_date',
        ),
    ]
