# Generated by Django 5.2.6 on 2025-11-06 02:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_remove_donationdrive_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationdrive',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='donationdrive',
            name='waste_type',
            field=models.CharField(default='', help_text='Type of waste this drive collects (e.g. Food, Plastic, Oil)', max_length=50),
        ),
        migrations.AlterField(
            model_name='donationparticipation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
