# Generated by Django 5.2.6 on 2025-11-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_rewardtransaction_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='points_required',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
