# Generated by Django 5.1.1 on 2025-11-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_voucher_points_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vouchers/'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='name',
            field=models.CharField(default='Voucher Name', max_length=100),
        ),
    ]
