# Generated by Django 5.1.1 on 2025-11-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_voucher_description_voucher_image_voucher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
