# Generated by Django 5.1.1 on 2025-11-03 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_alter_voucher_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardredemption',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
