# Generated by Django 5.1.1 on 2025-11-03 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_rewardredemption_is_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardpoint',
            options={'verbose_name': 'Reward Point', 'verbose_name_plural': 'Reward Points'},
        ),
        migrations.AlterModelOptions(
            name='rewardredemption',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='rewardtransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ['points_required', '-created_at']},
        ),
        migrations.AddField(
            model_name='rewardredemption',
            name='voucher',
            field=models.ForeignKey(blank=True, help_text='Voucher at the time of redemption (nullable if deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redemptions', to='rewards.voucher'),
        ),
        migrations.AlterField(
            model_name='rewardredemption',
            name='item_name',
            field=models.CharField(help_text="Human-friendly name snapshot at redemption time (e.g., '₱50 Discount Voucher').", max_length=255),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['user', 'created_at'], name='rewards_rew_user_id_8de60d_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardredemption',
            index=models.Index(fields=['is_used'], name='rewards_rew_is_used_f0d2e8_idx'),
        ),
    ]
